FROM node:14 AS frontend
WORKDIR /doit
COPY package.json yarn.lock /doit
RUN yarn install
COPY . .
RUN yarn run build

FROM nginx:1.19.5
# for health check
RUN apt-get update && apt-get install -y curl
ADD nginx/custom.conf /etc/nginx/nginx.conf
COPY --from=frontend /doit/public /doit/public/
EXPOSE 80
ENTRYPOINT ["nginx", "-g", "daemon off;"]