FROM ruby:2.6.3

RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    postgresql-client \
    && gem install bundler

ENV APP_HOME /doit
RUN mkdir -p $APP_HOME
WORKDIR $APP_HOME
COPY Gemfile /doit/
RUN bundle install
ADD . $APP_HOME
RUN mkdir -p $APP_HOME/tmp/pids
RUN mkdir -p $APP_HOME/tmp/sockets

VOLUME $APP_HOME/tmp