source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.7.6'

gem 'jbuilder', '~> 2.7'
gem 'puma'
gem 'rails', '6.0.4'
gem 'bootsnap', '>= 1.4.2', require: false
gem 'bcrypt'
gem 'date_validator'
gem 'nokogiri'
gem 'rails-i18n'
gem 'valid_email2'
gem 'carrierwave'
gem 'mini_magick'
gem 'dotenv-rails'
gem 'omniauth'
gem 'omniauth-twitter'
gem 'omniauth-facebook'
gem 'omniauth-google-oauth2'
gem 'rack-cors'
gem 'net-http'

# Sprockets4.0だと、app/assetsディレクトリを削除するとSprockets::Railtie::ManifestNeededErrorが発生する
gem 'sprockets', '~> 3.7.2'

group :development, :test do
  gem 'sqlite3', '1.4.2'
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  gem 'awesome_print'
  gem 'pry-rails'
end

group :development do
  gem 'listen', '~> 3.2'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem 'web-console', '>= 3.3.0'
  gem 'spring-commands-rspec'
  gem 'bullet'
end

group :test do
  gem 'factory_bot_rails'
  gem 'rspec-rails'
  gem 'selenium-webdriver'
  gem 'webdrivers'
  gem 'rspec_junit_formatter'
end

group :production do
  gem 'pg', '1.1.4'
end
